global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'docker'
    static_configs:
      - targets: ['backend:80', 'frontend:80']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['localhost:8085']
    metrics_path: '/metrics'